apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-multi-step
spec:
  steps:
    - name: write-hello
      image: busybox
      script: |
        #!/bin/sh
        date
        pwd
        echo "Hello World" > hello.txt
    - name: say-hello
      image: alpine
      script: |
        #!/bin/sh
        date
        pwd
        cat hello.txt
